config/routes.rb
Rails.application.routes.draw do

  root :to => "carp#index"
  resources :sites
  resources :records
  get 'statement' => "carp#statement"
  get 'testing' => "calculate#day"
  get 'specific' => "calculate#year"
  get 'river-length' => "sites#riverLength"

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
     def index
        @records = Record.all
    end
    def new
        @record = Record.new
    end
    def create
        @record = Record.new(record_params)
        past_record = Record.where(:site_serial => @record.site_serial, :date => @record.date).first
        if (!past_record)
            @record.save
        end

        redirect_to :action => :index
    end
    def destroy
        @record = Record.find(params[:id])
        @record.destroy

        redirect_to :action => :index
    end

    private
    def record_params
        params.require(:record).permit(:site_serial, :date, :streamflow, :streamflow_spike, :water_temperature)
    end

end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/index.html.erb
<div class="container-fluie width-limit-md">
    <table>
    <thead>
        <tr>
            <td>Site serial</td>
            <td>日期</td>
            <td>流速(ft/sec)</td>
            <td>流速spike(ft/sec)</td>
            <td>水溫(度C)</td>
            <td>gdd</td>
            <td>predicted length for C. idella</td>
            <td>predicted length for H. molitrix</td>
            <td>predicted length for M .piceus</td>
            <td>動作</td>
        </tr>
    </thead>
    <tbody>
        <% @records.each do |record| %>
            <tr>
                <td><%= record.site_serial %></td>
                <td><%= record.date %></td>
                <td><%= record.streamflow %></td>
                <td><%= record.streamflow_spike %></td>
                <td><%= record.water_temperature %></td>
                <td><%= record.gdd %></td>
                <td><%= record.predicted_length_c %></td>
                <td><%= record.predicted_length_h %></td>
                <td><%= record.predicted_length_m %></td>
                <td><%= link_to 'Delete', record_path(record), :method => :delete %></td>
            </tr>
        <% end %>
    </tbody>
    </table>
    <%= link_to 'New record', :controller => 'records', :action => 'new' %>
</div>

app/views/records/new.html.erb
<div class="container-fluie width-limit-md">
    <%= form_for @record, :url => { :controller => 'records', :action => 'create' } do |f| %>
        <%= f.label :site_serial, "Site serial" %>
        <%= f.text_field :site_serial %>

        <%= f.label :date, "日期" %>
        <%= f.text_field :date %>

        <%= f.label :streamflow, "流速(ft/sec)" %>
        <%= f.text_field :streamflow %>

        <%= f.label :streamflow_spike, "流速spike(ft/sec)" %>
        <%= f.text_field :streamflow_spike %>

        <%= f.label :water_temperature, "水溫(度C)" %>
        <%= f.text_field :water_temperature %>

        <%= f.submit "Create" %>
    <% end %>
</div>