config/routes.rb
Rails.application.routes.draw do

  root :to => "carp#index"
  resources :sites
  resources :records
  get 'statement' => "carp#statement"
  get 'testing' => "calculate#day"
  get 'specific' => "calculate#year"
  get 'river-length' => "sites#riverLength"

end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
    def index
        @sites = Site.all
    end
    def new
        @site = Site.new
    end
    def create
        @site = Site.new(site_params)
        past_site = Site.where(:serial => @site.serial).first
        if (!past_site)
            @site.save
        end

        redirect_to :action => :index
    end
    def destroy
        @site = Site.find(params[:id])
        @site.destroy

        redirect_to :action => :index
    end

    def riverLength
        @site = Site.where('serial' => params[:serial]).first
        render :text => @site.river_length
    end

    private
    def site_params
        params.require(:site).permit(:serial, :name, :river_length, :reg_square, :reg_linear, :reg_const)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/index.html.erb
<div class="container-fluie width-limit-md">
    <table>
    <thead>
        <tr>
            <td>編號</td>
            <td>名稱</td>
            <td>河川長度(公尺)</td>
            <td>回歸二次項</td>
            <td>回歸一次項</td>
            <td>回歸常數項</td>
            <td>動作</td>
        </tr>
    </thead>
    <tbody>
        <% @sites.each do |site| %>
            <tr>
                <td><%= site.serial %></td>
                <td><%= site.name %></td>
                <td><%= site.river_length %></td>
                <td><%= site.reg_square %></td>
                <td><%= site.reg_linear %></td>
                <td><%= site.reg_const %></td>
                <td><%= link_to 'Delete', site_path(site), :method => :delete %></td>
            </tr>
        <% end %>
    </tbody>
    </table>
    <%= link_to 'New site', :controller => 'sites', :action => 'new' %>
</div>

app/views/sites/new.html.erb
<div class="container-fluie width-limit-md">
    <%= form_for @site, :url => { :controller => 'sites', :action => 'create' } do |f| %>
        <%= f.label :serial, "Serial" %>
        <%= f.text_field :serial %>

        <%= f.label :name, "Name" %>
        <%= f.text_field :name %>

        <%= f.label :river_length, "河川長度(公尺)" %>
        <%= f.text_field :river_length %>

        <%= f.label :reg_square, "二次項" %>
        <%= f.text_field :reg_square %>

        <%= f.label :reg_linear, "一次項" %>
        <%= f.text_field :reg_linear %>

        <%= f.label :reg_const, "常數項" %>
        <%= f.text_field :reg_const %>


        <%= f.submit "Create" %>
    <% end %>
</div>